-- Name: views.article
-- Created: 2015-04-24 18:17:20
-- Updated: 2015-04-24 18:17:20

CREATE VIEW views.article
AS
SELECT 
	a.id as article_id,
	sa.id as supplier_article_id,
	sa.article_id as  supplier_article_article_id,
	sa.sku as supplier_article_sku,
	sa.supplier_id as supplier_id,
	s."name" as supplier_name ,
	sa.active as supplier_article_active,
	sa.ean as supplier_article_ean,
	sa.image_url as supplier_article_image_url,
	sa.partner_shop_url as "supplier_article_partner_shop_url",
	sa.manufacturer_sku as supplier_article_manufacturer_sku,
	sa.date_created as "supplier_article_date_created",
	sa.last_updated as "supplier_article_last_updated",
	sa.retail_price as "supplier_article_retail_price",
	sa.purchase_price as "supplier_article_purchase_price",
	cast(a.description as varchar(4000)) as "article_description",
	a.title as article_title,
	case when b.name is not null then b.name else a.brand end as article_brand,
	a.color as article_color,
	a."size" as article_size,
	a.sku as article_sku,
	a.date_created as "article_date_created",
	a.last_updated as "aarticle_last_updated",
	a.country_of_origin as article_country_of_origin,
	a.del as "article_del",
	a.weight as article_weight,
	a.ean as article_ean,
	a.model_id as article_model_id,
	a.manufacturer_color_code as article_manufacturer_color_code,
	a.manufacturer_color_name as article_manufacturer_color_name,
	a.manufacturer_sku as article_manufacturer_sku,
	a.manufacturer_alternative_sku as article_manufacturer_alternative_sku,
	a.manufacturer_size as article_manufacturer_size,
	prices.retail_min_price_NL,
	prices.retail_max_price_NL,
	prices.retail_min_price_DE,
	prices.retail_max_price_DE,
	prices.retail_min_price_AT,
	prices.retail_max_price_AT,
	prices.retail_min_price_CH,
	prices.retail_max_price_CH,
	prices.retail_min_price_SE,
	prices.retail_max_price_SE,
	prices.retail_min_price_DK,
	prices.retail_max_price_DK,
	CASE WHEN cg1.title_de is not null THEN cg1.title_de ELSE ad.commodity_group1 END as commodity_group1,
	CASE WHEN cg2.title_de is not null THEN cg2.title_de ELSE ad.commodity_group2 END as commodity_group2,
	CASE WHEN cg3.title_de is not null THEN cg3.title_de ELSE ad.commodity_group3 END as commodity_group3,
	CASE WHEN cg4.title_de is not null THEN cg4.title_de ELSE ad.commodity_group4 END as commodity_group4,
	CASE WHEN cg5.title_de is not null THEN cg5.title_de ELSE ad.commodity_group5 END as commodity_group5,
	ad.commodity_group6,
	left(ad.amidala_categories  ,4000) as amidala_categories  ,
	left(ad.amidala_check  ,4000) as amidala_check  ,
	left(ad.amidala_deactive  ,4000) as amidala_deactive  ,
	left(ad.article_name  ,4000) as article_name  ,
	left(ad.basic_unit  ,4000) as basic_unit  ,
	left(case when b.name is not null then b.name else a.brand  end ,4000) as brand  ,
	left(ad.check_details  ,4000) as check_details  ,
	left(ad.check_fitting  ,4000) as check_fitting  ,
	left(ad.check_material_style_attributes  ,4000) as check_material_style_attributes  ,
	left(ad.check_schulung  ,4000) as check_schulung  ,
	left(ad.color1  ,4000) as color1  ,
	left(ad.color1_shade  ,4000) as color1_shade  ,
	left(ad.country_of_origin  ,4000) as country_of_origin  ,
	left(ad.country_of_production  ,4000) as country_of_production  ,
	left(ad.customs_tariff_number  ,4000) as customs_tariff_number  ,
	left(ad.ean  ,4000) as ean  ,
	left(ad.model_o_id  ,4000) as model_o_id  ,
	left(ad.nos  ,4000) as nos  ,
	left(ad.o_classid  ,4000) as o_classid  ,
	left(ad.o_classname  ,4000) as o_classname  ,
	left(ad.o_creationdate  ,4000) as o_creationdate  ,
	left(ad.o_id  ,4000) as o_id  ,
	left(ad.o_index  ,4000) as o_index  ,
	left(ad.o_key  ,4000) as o_key  ,
	left(ad.o_modificationdate  ,4000) as o_modificationdate  ,
	left(ad.o_parentid  ,4000) as o_parentid  ,
	left(ad.o_path  ,4000) as o_path  ,
	left(ad.o_published  ,4000) as o_published  ,
	left(ad.o_type  ,4000) as o_type  ,
	left(ad.o_usermodification  ,4000) as o_usermodification  ,
	left(ad.o_userowner  ,4000) as o_userowner  ,
	left(ad.oo_classid  ,4000) as oo_classid  ,
	left(ad.oo_classname  ,4000) as oo_classname  ,
	left(ad.oo_id  ,4000) as oo_id  ,
	left(ad.pic1  ,4000) as pic1  ,
	left(ad.pic2  ,4000) as pic2  ,
	left(ad.pic3 ,4000) as pic3 ,
	left(ad.pic4  ,4000) as pic4  ,
	left(ad.pic5  ,4000) as pic5  ,
	left(ad.price_retail_at  ,4000) as price_retail_at  ,
	left(ad.price_retail_ch  ,4000) as price_retail_ch  ,
	left(ad.price_retail_de  ,4000) as price_retail_de  ,
	left(ad.processing_code  ,4000) as processing_code  ,
	left(ad.purchase_price  ,4000) as purchase_price  ,
	left(ad.season  ,4000) as season  ,
	left(ad.supplier_article_name  ,4000) as supplier_article_name  ,
	left(ad.supplier_color_code  ,4000) as supplier_color_code  ,
	left(ad.supplier_color_name  ,4000) as supplier_color_name  ,
	left(ad.supplier_finish  ,4000) as supplier_finish  ,
	left(ad.supplier_length  ,4000) as supplier_length  ,
	left(ad.supplier_size  ,4000) as supplier_size  ,
	left(ad.supplier_sku  ,4000) as supplier_sku  ,
	left(ad.net_weight  ,4000) as net_weight  ,
	left(ad.special_charakteristics_accessories  ,4000) as special_charakteristics_accessories  ,
	left(ad.gross_weight  ,4000) as gross_weight  ,
	left(ad.buyer  ,4000) as buyer  ,
	left(ad.FittingHoselenght_pants,4000) as "F_Hose_lenght_pants",
	left(ad.FittingHosefit,4000) as "F_Hose_fit",
	left(ad.FittingHosewaist_line,4000) as "F_Hose_waist_line",
	left(ad.FittingHosecrotch,4000) as "F_Hose_crotch",
	left(ad.FittingHosefitting_trousers,4000) as "F_Hose_fitting_trousers",
	left(ad.FittingHosefitting_extras,4000) as "F_Hose_fitting_extras",
	left(ad.FittingHosefitting_normalizer,4000) as "F_Hose_fitting_normalizer",
	left(ad.FittingKonfektionfit,4000) as "F_Konfektion_fit",
	left(ad.FittingKonfektionblazer_length,4000) as "F_Konfektion_blazer_length",
	left(ad.FittingKonfektionfitting_trousers,4000) as "F_Konfektion_fitting_trousers",
	left(ad.FittingKonfektionfitting_extras,4000) as "F_Konfektion_fitting_extras",
	left(ad.FittingKonfektionfitting_normalizer,4000) as "F_Konfektion_fitting_normalizer",
	left(ad.FittingKonfektionfitting_top,4000) as "F_Konfektion_fitting_top",
	left(ad.FittingKonfektionwaist_line,4000) as "F_Konfektion_waist_line",
	left(ad.FittingOberteilsleeve_length,4000) as "F_Oberteil_sleeve_length",
	left(ad.FittingOberteilfit,4000) as "F_Oberteil_fit",
	left(ad.FittingOberteilfitting_top,4000) as "F_Oberteil_fitting_top",
	left(ad.FittingOberteilfitting_extras,4000) as "F_Oberteil_fitting_extras",
	left(ad.FittingOberteilfitting_normalizer,4000) as "F_Oberteil_fitting_normalizer",
	left(ad.FittingOberteillenght_top,4000) as "F_Oberteil_lenght_top",
	left(ad.FittingOberteilwidth_top,4000) as "F_Oberteil_width_top",
	left(ad.FittingOutdoorfit,4000) as "F_Outdoor_fit",
	left(ad.FittingOutdoorlength_coat,4000) as "F_Outdoor_length_coat",
	left(ad.FittingOutdoorfitting_extras,4000) as "F_Outdoor_fitting_extras",
	left(ad.FittingOutdoorfitting_normalizer,4000) as "F_Outdoor_fitting_normalizer",
	left(ad.FittingOutdoorfitting_top,4000) as "F_Outdoor_fitting_top",
	left(ad.FittingSchuhwidth_shoes,4000) as "F_Schuh_width_shoes",
	left(ad.FittingSchuhfitting_shoes,4000) as "F_Schuh_fitting_shoes",
	left(ad.FittingSchuhfitting_normalizer,4000) as "F_Schuh_fitting_normalizer",
	left(ad.FittingSchuhfitting_extras,4000) as "F_Schuh_fitting_extras",
	left(ad.DetailsGuertelbelt_width_cm,4000) as "D_Guertel_belt_width_cm",
	left(ad.DetailsGuertelclosure_accessories,4000) as "D_Guertel_closure_accessories",
	left(ad.DetailsGuertelspecial_charakteristics_accessories,4000) as "D_Guertel_special_charakteristics_accessories",
	left(ad.DetailsGuerteldetails,4000) as "D_Guertel_details",
	left(ad.DetailsHandschuhelenght_cm,4000) as "D_Handschuhe_lenght_cm",
	left(ad.DetailsHandschuheclosure_accessories,4000) as "D_Handschuhe_closure_accessories",
	left(ad.DetailsHandschuhespecial_charakteristics_accessories,4000) as "D_Handschuhe_special_charakteristics_accessories",
	left(ad.DetailsHandschuhedetails,4000) as "D_Handschuhe_details",
	left(ad.DetailsHoseclosure_trousers,4000) as "D_Hose_closure_trousers",
	left(ad.DetailsHosetrousers_pocket,4000) as "D_Hose_trousers_pocket",
	left(ad.DetailsHosecrease,4000) as "D_Hose_crease",
	left(ad.DetailsHosetuck,4000) as "D_Hose_tuck",
	left(ad.DetailsHosespecial_attributes_trousers,4000) as "D_Hose_special_attributes_trousers",
	left(ad.DetailsHosedetails,4000) as "D_Hose_details",
	left(ad.DetailsKonfektioncollar,4000) as "D_Konfektion_collar",
	left(ad.DetailsKonfektionclosure_tops,4000) as "D_Konfektion_closure_tops",
	left(ad.DetailsKonfektionclosure_trousers,4000) as "D_Konfektion_closure_trousers",
	left(ad.DetailsKonfektionslit,4000) as "D_Konfektion_slit",
	left(ad.DetailsKonfektionpockets_tops,4000) as "D_Konfektion_pockets_tops",
	left(ad.DetailsKonfektiontrousers_pocket,4000) as "D_Konfektion_trousers_pocket",
	left(ad.DetailsKonfektioncrease,4000)as "D_Konfektion_crease",
	left(ad.DetailsKonfektiontuck,4000) as "D_Konfektion_tuck",
	left(ad.DetailsKonfektionspecial_attributes_tops,4000) as "D_Konfektion_special_attributes_tops",
	left(ad.DetailsKonfektionspecial_attributes_trousers,4000) as "D_Konfektion_special_attributes_trousers",
	left(ad.DetailsKonfektiondetails,4000) as "D_Konfektion_details",
	left(ad.DetailsKopfaccessoirescircumference_cm,4000) as "D_Kopfaccessoires_circumference_cm",
	left(ad.DetailsKopfaccessoiresclosure_accessories,4000) as "D_Kopfaccessoires_closure_accessories",
	left(ad.DetailsKopfaccessoiresdetails,4000) as "D_Kopfaccessoires_details",
	left(ad.DetailsKrawatteFliegelenght_cm ,4000)as "D_Krawatte_Fliege_lenght_cm",
	left(ad.DetailsKrawatteFliegewidth_cm ,4000)as "D_Krawatte_Fliege_width_cm",
	left(ad.DetailsKrawatteFliegespecial_charakteristics_accessories ,4000)as "D_Krawatte_Fliege_special_charakteristics_accessories",
	left(ad.DetailsKrawatteFliegedetails ,4000)as "D_Krawatte_Fliege_details",
	left(ad.DetailsOberteiltype_print,4000) as "D_Oberteil_type_print",
	left(ad.DetailsOberteilclosure_tops,4000) as "D_Oberteil_closure_tops",
	left(ad.DetailsOberteilpockets_tops,4000) as "D_Oberteil_pockets_tops",
	left(ad.DetailsOberteilcollar,4000) as "D_Oberteil_collar",
	left(ad.DetailsOberteilhood,4000) as "D_Oberteil_hood",
	left(ad.DetailsOberteilslit,4000) as "D_Oberteil_slit",
	left(ad.DetailsOberteilspecial_attributes_tops,4000) as "D_Oberteil_special_attributes_tops",
	left(ad.DetailsOberteildetails,4000) as "D_Oberteil_details",
	left(ad.DetailsOberteilquality_print,4000) as "D_Oberteil_quality_print",
	left(ad.DetailsOutdoorclosure_tops,4000) as "D_Outdoor_closure_tops",
	left(ad.DetailsOutdoorcollar,4000) as "D_Outdoor_collar",
	left(ad.DetailsOutdoorslit,4000) as "D_Outdoor_slit",
	left(ad.DetailsOutdoorhood,4000) as "D_Outdoor_hood",
	left(ad.DetailsOutdoorpockets_tops,4000) as "D_Outdoor_pockets_tops",
	left(ad.DetailsOutdoorspecial_attributes_tops,4000) as "D_Outdoor_special_attributes_tops",
	left(ad.DetailsOutdoordetails,4000) as "D_Outdoor_details",
	left(ad.DetailsSchuhtoe_shoes,4000) as "D_Schuh_toe_shoes",
	left(ad.DetailsSchuhclosure_shoes,4000) as "D_Schuh_closure_shoes",
	left(ad.DetailsSchuhheight_upper_cm,4000) as "D_Schuh_height_upper_cm",
	left(ad.DetailsSchuhwidth_upper_cm,4000) as "D_Schuh_width_upper_cm",
	left(ad.DetailsSchuhheight_heel_cm,4000) as "D_Schuh_height_heel_cm",
	left(ad.DetailsSchuhheel,4000) as "D_Schuh_heel",
	left(ad.DetailsSchuhfootbed,4000) as "D_Schuh_footbed",
	left(ad.DetailsSchuhspecial_attributes_shoes,4000) as "D_Schuh_special_attributes_shoes",
	left(ad.DetailsSchuhdetails,4000) as "D_Schuh_details",
	left(ad.DetailsSockendetails,4000)as "DetailsSocken_details",
	left(ad.DetailsTuecherSchallenght_cm ,4000)as "D_Tuecher_Schal_lenght_cm",
	left(ad.DetailsTuecherSchalwidth_cm ,4000)as "D_Tuecher_Schal_width_cm",
	left(ad.DetailsTuecherSchaldiameter_cm ,4000)as "D_Tuecher_Schal_diameter_cm",
	left(ad.DetailsTuecherSchalspecial_charakteristics_accessories ,4000)as "D_Tuecher_Schal_special_charakteristics_accessories",
	left(ad.DetailsTuecherSchaldetails ,4000)as "D_Tuecher_Schal_details",
	left(ad.DetailsUnterhosespecial_characteristics_underwear,4000) as "D_Unterhose_special_characteristics_underwear",
	left(ad.DetailsUnterhosedetails,4000) as "D_Unterhose_details",
	left(ad.MaterialStyleAccessoiresGuertelpercentage1_upper_fabric,4000) as "MStyle_Accessoires_Guertel_percentage1_upper_fabric",
	left(ad.MaterialStyleAccessoiresGuertelupper_fabric_share1,4000) as "MStyle_Accessoires_Guertel_upper_fabric_share1",
	left(ad.MaterialStyleAccessoiresGuertelpattern,4000) as "MStyle_Accessoires_Guertel_pattern",
	left(ad.MaterialStyleAccessoiresGuertelfinish_metal,4000) as "MStyle_Accessoires_Guertel_finish_metal",
	left(ad.MaterialStyleAccessoiresGuertelquality_upper_fabric,4000) as "MStyle_Accessoires_Guertel_quality_upper_fabric",
	left(ad.MaterialStyleAccessoiresGuertelquality_finishing,4000) as "MStyle_Accessoires_Guertel_quality_finishing",
	left(ad.MaterialStyleAccessoiresGuerteloutfittery_occasion,4000)as "MStyle_Accessoires_Guertel_outfittery_occasion",
	left(ad.MaterialStyleAccessoiresGuerteloutfittery_style,4000) as "MStyle_Accessoires_Guertel_outfittery_style",
	left(ad.MaterialStyleAccessoiresGuertelpercentage2_upper_fabric,4000) as "MStyle_Accessoires_Guertel_percentage2_upper_fabric",
	left(ad.MaterialStyleAccessoiresGuertelupper_fabric_share2,4000) as "MStyle_Accessoires_Guertel_upper_fabric_share2",
	left(ad.MaterialStyleAccessoiresTextilpercentage1_upper_fabric,4000) as "MStyle_Accessoires_Textil_percentage1_upper_fabric",
	left(ad.MaterialStyleAccessoiresTextilpercentage2_upper_fabric,4000) as "MStyle_Accessoires_Textil_percentage2_upper_fabric",
	left(ad.MaterialStyleAccessoiresTextilupper_fabric_share2,4000) as "MStyle_Accessoires_Textil_upper_fabric_share2",
	left(ad.MaterialStyleAccessoiresTextilpercentage1_material_lining,4000) as "MStyle_Accessoires_Textil_percentage1_material_lining",
	left(ad.MaterialStyleAccessoiresTextilmaterial_lining_share1,4000) as "MStyle_Accessoires_Textil_material_lining_share1",
	left(ad.MaterialStyleAccessoiresTextilmaterialname_fabric_upper,4000) as "MStyle_Accessoires_Textil_materialname_fabric_upper",
	left(ad.MaterialStyleAccessoiresTextilcare_instructions,4000) as "MStyle_Accessoires_Textil_care_instructions",
	left(ad.MaterialStyleAccessoiresTextilproduction_information,4000) as "MStyle_Accessoires_Textil_production_information",
	left(ad.MaterialStyleAccessoiresTextilpattern,4000) as "MStyle_Accessoires_Textil_pattern",
	left(ad.MaterialStyleAccessoiresTextilfineness_of_material,4000) as "MStyle_Accessoires_Textil_fineness_of_material",
	left(ad.MaterialStyleAccessoiresTextilfinish_textile,4000) as "MStyle_Accessoires_Textil_finish_textile",
	left(ad.MaterialStyleAccessoiresTextilquality_upper_fabric,4000) as "MStyle_Accessoires_Textil_quality_upper_fabric",
	left(ad.MaterialStyleAccessoiresTextilquality_finishing,4000) as "MStyle_Accessoires_Textil_quality_finishing",
	left(ad.MaterialStyleAccessoiresTextiloutfittery_style,4000) as "MStyle_Accessoires_Textil_outfittery_style",
	left(ad.MaterialStyleAccessoiresTextiloutfittery_occasion ,4000)as "MStyle_Accessoires_Textil_outfittery_occasion",
	left(ad.MaterialStyleAccessoiresTextilupper_fabric_share1,4000) as "MStyle_Accessoires_Textil_upper_fabric_share1",
	left(ad.MaterialStyleAccessoiresTextilpercentage3_upper_fabric,4000) as "MStyle_Accessoires_Textil_percentage3_upper_fabric",
	left(ad.MaterialStyleAccessoiresTextilupper_fabric_share3,4000) as "MStyle_Accessoires_Textil_upper_fabric_share3",
	left(ad.MaterialStyleAccessoiresTextilpercentage2_material_lining,4000) as "MStyle_Accessoires_Textil_percentage2_material_lining",
	left(ad.MaterialStyleAccessoiresTextilmaterial_lining_share2,4000) as "MStyle_Accessoires_Textil_material_lining_share2",
	left(ad.MaterialStyleAccessoiresTextiloutfittery_upper_fabric,4000) as "MStyle_Accessoires_Textil_outfittery_upper_fabric",
	left(ad.MaterialStyleAccessoiresTextillining_textile,4000) as "MStyle_Accessoires_Textil_lining_textile",
	left(ad.MaterialStyleBekleidungpattern,4000) as "MStyle_Bekleidung_pattern",
	left(ad.MaterialStyleBekleidungcare_instructions,4000) as "MStyle_Bekleidung_care_instructions",
	left(ad.MaterialStyleBekleidungproduction_information,4000) as "MStyle_Bekleidung_production_information",
	left(ad.MaterialStyleBekleidunglining_textile,4000) as "MStyle_Bekleidung_lining_textile",
	left(ad.MaterialStyleBekleidungmaterialname_fabric_upper,4000) as "MStyle_Bekleidung_materialname_fabric_upper",
	left(ad.MaterialStyleBekleidungoutfittery_upper_fabric,4000) as "MStyle_Bekleidung_outfittery_upper_fabric",
	left(ad.MaterialStyleBekleidungfineness_of_material,4000) as "MStyle_Bekleidung_fineness_of_material",
	left(ad.MaterialStyleBekleidungquality_upper_fabric,4000) as "MStyle_Bekleidung_quality_upper_fabric",
	left(ad.MaterialStyleBekleidungquality_finishing,4000) as "MStyle_Bekleidung_quality_finishing",
	left(ad.MaterialStyleBekleidungfinish_textile,4000) as "MStyle_Bekleidung_finish_textile",
	left(ad.MaterialStyleBekleidungelasticity ,4000)as "MStyle_Bekleidung_elasticity",
	left(ad.MaterialStyleBekleidungoutfittery_style,4000) as "MStyle_Bekleidung_outfittery_style",
	left(ad.MaterialStyleBekleidungoutfittery_occasion,4000) as "MStyle_Bekleidung_outfittery_occasion",
	left(ad.MaterialStyleBekleidungupper_fabric_share1,4000) as "MStyle_Bekleidung_upper_fabric_share1",
	left(ad.MaterialStyleBekleidungpercentage1_upper_fabric,4000) as "MStyle_Bekleidung_percentage1_upper_fabric",
	left(ad.MaterialStyleBekleidungpercentage2_upper_fabric,4000) as "MStyle_Bekleidung_percentage2_upper_fabric",
	left(ad.MaterialStyleBekleidungupper_fabric_share2,4000) as "MStyle_Bekleidung_upper_fabric_share2",
	left(ad.MaterialStyleBekleidungmaterial_lining_share1,4000) as "MStyle_Bekleidung_material_lining_share1",
	left(ad.MaterialStyleBekleidungpercentage1_material_lining,4000) as "MStyle_Bekleidung_percentage1_material_lining",
	left(ad.MaterialStyleBekleidungpercentage3_upper_fabric,4000) as "MStyle_Bekleidung_percentage3_upper_fabric",
	left(ad.MaterialStyleBekleidungupper_fabric_share3,4000) as "MStyle_Bekleidung_upper_fabric_share3",
	left(ad.MaterialStyleBekleidungpercentage2_material_lining,4000) as "MStyle_Bekleidung_percentage2_material_lining",
	left(ad.MaterialStyleBekleidungmaterial_lining_share2,4000) as "MStyle_Bekleidung_material_lining_share2",
	left(ad.MaterialStyleBekleidungpercentage4_upper_fabric,4000) as "MStyle_Bekleidung_percentage4_upper_fabric",
	left(ad.MaterialStyleBekleidungupper_fabric_share4,4000) as "MStyle_Bekleidung_upper_fabric_share4",
	left(ad.MaterialStyleSchuheupper_material_shoes,4000) as "MStyle_Schuhe_upper_material_shoes",
	left(ad.MaterialStyleSchuhelining_shoes,4000) as "MStyle_Schuhe_lining_shoes",
	left(ad.MaterialStyleSchuheinnersole_shoes,4000) as "MStyle_Schuhe_innersole_shoes",
	left(ad.MaterialStyleSchuhesoletype_shoes,4000) as "MStyle_Schuhe_soletype_shoes",
	left(ad.MaterialStyleSchuhepattern,4000) as "MStyle_Schuhe_pattern",
	left(ad.MaterialStyleSchuhefinish_leather,4000) as "MStyle_Schuhe_finish_leather",
	left(ad.MaterialStyleSchuhequality_finishing,4000) as "MStyle_Schuhe_quality_finishing",
	left(ad.MaterialStyleSchuheoutfittery_style,4000) as "MStyle_Schuhe_outfittery_style",
	left(ad.MaterialStyleSchuheoutfittery_occasion,4000) as "MStyle_Schuhe_outfittery_occasion",
	left(ad.MaterialStyleSchuheproduction_information,4000) as "MStyle_Schuhe_production_information",
	left(ad.MaterialStyleSchuhesole_shoes,4000) as "MStyle_Schuhe_sole_shoes",
	left(ad.MaterialStyleSchuheinner_material_shoes,4000) as "MStyle_Schuhe_inner_material_shoes",
	left(ad.category_breadcrumbs,4000) as category_breadcrumbs,
	left(ad.category,4000) as category,
	at."Push Own Stock",
	se.quantity as current_inventory,
	se.reserved as current_reserved
FROM postgres.supplier_article sa
JOIN postgres.supplier s on s.id=sa.supplier_id
JOIN postgres.article a on sa.article_id=a.id
JOIN postgres.article_details ad on ad.id=sa.id
LEFT JOIN dwh.brands b on b.name_db = a.brand
LEFT JOIN postgres.stock_entry se on se.sku = sa.article_id AND se.stock_location_id = 2
LEFT JOIN dwh.commodity_group1 cg1 on cg1.commodity_group1 = ad.commodity_group1
LEFT JOIN dwh.commodity_group2 cg2 on cg2.commodity_group2 = ad.commodity_group2
LEFT JOIN dwh.commodity_group3 cg3 on cg3.commodity_group3 = ad.commodity_group3
LEFT JOIN dwh.commodity_group4 cg4 on cg4.commodity_group4 = ad.commodity_group4
LEFT JOIN dwh.commodity_group5 cg5 on cg5.commodity_group5 = ad.commodity_group5
LEFT JOIN
(
	SELECT
	at.article_attributes_id, 
	cast(ar.name as string) as "Push Own Stock" 
	FROM postgres.article_attribute at 
	JOIN postgres.attribute ar on ar.id = at.attribute_id 
	WHERE ar.property_id = 60716143	 
	GROUP BY at.article_attributes_id, ar.name
) at on at.article_attributes_id = a.id
LEFT JOIN 
(
	SELECT 
	ap.article_id,
	min(case when ap.iso_country_code = 'NL' then ap.price else null end) as retail_min_price_NL,
	max(case when ap.iso_country_code = 'NL' then ap.price else null end) as retail_max_price_NL,
	min(case when ap.iso_country_code = 'DE' then ap.price else null end) as retail_min_price_DE,
	max(case when ap.iso_country_code = 'DE' then ap.price else null end) as retail_max_price_DE,
	min(case when ap.iso_country_code = 'AT' then ap.price else null end) as retail_min_price_AT,
	max(case when ap.iso_country_code = 'AT' then ap.price else null end) as retail_max_price_AT,
	min(case when ap.iso_country_code = 'CH' then ap.price else null end) as retail_min_price_CH,
	max(case when ap.iso_country_code = 'CH' then ap.price else null end) as retail_max_price_CH,
	min(case when ap.iso_country_code = 'SE' then ap.price else null end) as retail_min_price_SE,
	max(case when ap.iso_country_code = 'SE' then ap.price else null end) as retail_max_price_SE,
	min(case when ap.iso_country_code = 'DK' then ap.price else null end) as retail_min_price_DK,
	max(case when ap.iso_country_code = 'DK' then ap.price else null end) as retail_max_price_DK
	FROM postgres.article_price ap
	GROUP BY ap.article_id
) prices on prices.article_id = a.id

WHERE exists (SELECT 1 from postgres.order_position op WHERE op.supplier_article_id = sa.id)
OR sa.supplier_id = 15


