-- Name: views.order_position
-- Created: 2015-04-24 18:19:41
-- Updated: 2015-04-24 18:19:41

CREATE VIEW views.order_position 
AS
SELECT 
	coa.order_position_id as id,
	coa.order_article_state_number as state,
	null as version,
	coa.article_id,
	coa.date_created,
	null as last_updated,
	coa.order_id,
	coa.articles_picked as quantity,
	coa.supplier_article_id,
	CASE WHEN coa.articles_picked > 0 THEN coa.cost_picked/coa.articles_picked ELSE 0 END as purchase_price,
	CAST(CASE WHEN coa.articles_picked > 0 THEN coa.sales_picked*co.exchange_rate/coa.articles_picked ELSE 0 END as double) as retail_price,
	coa.date_returned,
	coa.date_shipped,
	coa.supplier_order_number,
	coa.date_incoming,
	coa.date_returned_online,
	coa.group_id,
	coa.order_position_count as order_positions_idx,
	coa.track_and_trace_number,
	coa.stock_location_id,
	coa.date_picked,
	coa.date_cancelled as date_canceled,
	coa.date_lost, 
	co.currency_code,
	coa.sales_picked as retail_price_euro,
	co.customer_preview_id as preview_id,
	co.preview_id as topic_box_id,
	coa.feedback_good_colour as feedback_Gute_Farbe,
	coa.feedback_good_quality as feedback_Gute_Qualitaet,
	coa.feedback_good_match_to_customers_style as feedback_Bisherigen_Stil_Gut_Getroffen,
	coa.feedback_damaged as feedback_Artikel_Defekt,
	coa.feedback_good_fit as feedback_Gute_Passform,
	coa.feedback_late_delivery as feedback_Zu_Spaet_Geliefert,
	coa.feedback_not_needed as feedback_Kein_Bedarf,
	coa.feedback_would_like_to_try_something_new as feedback_Lust_Was_Neues_Auszuprobieren,
	0 as feedback_Keine_Aussage1,
	0 as feedback_Keine_Aussage2,
	coa.feedback_too_outrageous feedback_Zu_Ausgefallen,
	coa.feedback_too_big as feedback_Zu_Gross,
	coa.feedback_too_short as feedback_Zu_Kurz,
	coa.feedback_too_cheap as feedback_Zu_Guenstig,
	coa.feedback_dont_like_the_brand as feedback_Marke_Gefaellt_Nicht,
	coa.feedback_too_simple as feedback_Zu_Schlicht,
	coa.feedback_bad_fit as feedback_Schnitt_Sitzt_Nicht,
	coa.feedback_dont_like_the_pattern as feedback_Muster_Gefaellt_Nicht,
	coa.feedback_too_small as feedback_Zu_Klein,
	coa.feedback_dont_like_the_colour as feedback_Farbe_Gefaellt_Nicht,
	0 as feedback_Zu_Kurz_Nochmal_Bestellt,
	0 as feedback_Zu_Gross_Nochmal_Bestellt,
	0 as feedback_Zu_Klein_Nochmal_Bestellt,
	0 as feedback_Zu_Lang_Nochmal_Bestellt,
	0 as feedback_Zu_Eng_Nochmal_Bestellt,
	0 as feedback_Zu_Weit_Nochmal_Bestellt,
	coa.feedback_too_low_quality as feedback_Zu_Minderwertig,
	coa.feedback_too_long as feedback_Zu_Lang,
	coa.feedback_too_tight as feedback_Zu_Eng,
	coa.feedback_too_wide as feedback_Zu_Weit,
	coa.feedback_too_expensive as feedback_Preis_Leistung,
	co.shipping_country
FROM bi.customer_order_articles coa
JOIN bi.customer_order co on co.order_id = coa.order_id


