-- Name: affilinet_adv.parseGetStatisticsPerPublisher
-- Created: 2015-04-24 18:07:23

CREATE VIRTUAL PROCEDURE affilinet_adv.parseGetStatisticsPerPublisher
(
   IN xmldata xml
)
RETURNS
(
   currency string,
   publisher_id string,
   publisher_url string,
   bonus_count_cancelled_count long,
   bonus_count_confirmed_count long,
   bonus_count_open_count long,
   bonus_network_fee_cancelled_value double,
   bonus_network_fee_confirmed_value double,
   bonus_network_fee_open_value double,
   bonus_publisher_commission_cancelled_value double,
   bonus_publisher_commission_confirmed_value double,
   bonus_publisher_commission_open_value double,
   click_outs_total_count_cancelled_count long,
   click_outs_total_count_confirmed_count long,
   click_outs_total_count_open_count long,
   click_outs_total_net_price_cancelled_value double,
   click_outs_total_net_price_confirmed_value double,
   click_outs_total_net_price_open_value double,
   click_outs_total_network_fee_cancelled_value double,
   click_outs_total_network_fee_confirmed_value double,
   click_outs_total_network_fee_open_value double,
   click_outs_total_publisher_commission_cancelled_value double,
   click_outs_total_publisher_commission_confirmed_value double,
   click_outs_total_publisher_commission_open_value double,
   clicks_gross_count long,
   clicks_net_count long,
   clicks_network_fee double,
   clicks_publisher_commission double,
   leads_total_count_cancelled_count long,
   leads_total_count_confirmed_count long,
   leads_total_count_open_count long,
   leads_total_net_price_cancelled_value double,
   leads_total_net_price_confirmed_value double,
   leads_total_net_price_open_value double,
   leads_total_network_fee_cancelled_value double,
   leads_total_network_fee_confirmed_value double,
   leads_total_network_fee_open_value double,
   leads_total_publisher_commission_cancelled_value double,
   leads_total_publisher_commission_confirmed_value double,
   leads_total_publisher_commission_open_value double,
   net_price_summary_cancelled_value double,
   net_price_summary_confirmed_value double,
   net_price_summary_open_value double,
   network_fee_summary_cancelled_value double,
   network_fee_summary_confirmed_value double,
   network_fee_summary_open_value double,
   publisher_commission_summary_cancelled_value double,
   publisher_commission_summary_confirmed_value double,
   publisher_commission_summary_open_value double,
   sales_total_count_cancelled_count long,
   sales_total_count_confirmed_count long,
   sales_total_count_open_count long,
   sales_total_net_price_cancelled_value string,
   sales_total_net_price_confirmed_value double,
   sales_total_net_price_open_value double,
   sales_total_network_fee_cancelled_value double,
   sales_total_network_fee_confirmed_value double,
   sales_total_network_fee_open_value double,
   sales_total_publisher_commission_cancelled_value double,
   sales_total_publisher_commission_confirmed_value double,
   sales_total_publisher_commission_open_value double,
   Views_GrossCount long,
   Views_NetCount long,
   Views_NetworkFee double,
   Views_PublisherCommission double,
   TotalCount integer
)
AS BEGIN
SELECT
xml_table.currency,
xml_table.publisher_id,
xml_table.publisher_url,
xml_table.bonus_count_cancelled_count,
xml_table.bonus_count_confirmed_count,
xml_table.bonus_count_open_count,
xml_table.bonus_network_fee_cancelled_value,
xml_table.bonus_network_fee_confirmed_value,
xml_table.bonus_network_fee_open_value,
xml_table.bonus_publisher_commission_cancelled_value,
xml_table.bonus_publisher_commission_confirmed_value,
xml_table.bonus_publisher_commission_open_value,
xml_table.click_outs_total_count_cancelled_count,
xml_table.click_outs_total_count_confirmed_count,
xml_table.click_outs_total_count_open_count,
xml_table.click_outs_total_net_price_cancelled_value,
xml_table.click_outs_total_net_price_confirmed_value,
xml_table.click_outs_total_net_price_open_value,
xml_table.click_outs_total_network_fee_cancelled_value,
xml_table.click_outs_total_network_fee_confirmed_value,
xml_table.click_outs_total_network_fee_open_value,
xml_table.click_outs_total_publisher_commission_cancelled_value,
xml_table.click_outs_total_publisher_commission_confirmed_value,
xml_table.click_outs_total_publisher_commission_open_value,
xml_table.clicks_gross_count,
xml_table.clicks_net_count,
xml_table.clicks_network_fee,
xml_table.clicks_publisher_commission,
xml_table.leads_total_count_cancelled_count,
xml_table.leads_total_count_confirmed_count,
xml_table.leads_total_count_open_count,
xml_table.leads_total_net_price_cancelled_value,
xml_table.leads_total_net_price_confirmed_value,
xml_table.leads_total_net_price_open_value,
xml_table.leads_total_network_fee_cancelled_value,
xml_table.leads_total_network_fee_confirmed_value,
xml_table.leads_total_network_fee_open_value,
xml_table.leads_total_publisher_commission_cancelled_value,
xml_table.leads_total_publisher_commission_confirmed_value,
xml_table.leads_total_publisher_commission_open_value,
xml_table.net_price_summary_cancelled_value,
xml_table.net_price_summary_confirmed_value,
xml_table.net_price_summary_open_value,
xml_table.network_fee_summary_cancelled_value,
xml_table.network_fee_summary_confirmed_value,
xml_table.network_fee_summary_open_value,
xml_table.publisher_commission_summary_cancelled_value,
xml_table.publisher_commission_summary_confirmed_value,
xml_table.publisher_commission_summary_open_value,
xml_table.sales_total_count_cancelled_count,
xml_table.sales_total_count_confirmed_count,
xml_table.sales_total_count_open_count,
xml_table.sales_total_net_price_cancelled_value,
xml_table.sales_total_net_price_confirmed_value,
xml_table.sales_total_net_price_open_value,
xml_table.sales_total_network_fee_cancelled_value,
xml_table.sales_total_network_fee_confirmed_value,
xml_table.sales_total_network_fee_open_value,
xml_table.sales_total_publisher_commission_cancelled_value,
xml_table.sales_total_publisher_commission_confirmed_value,
xml_table.sales_total_publisher_commission_open_value,
xml_table.Views_GrossCount,
xml_table.Views_NetCount,
xml_table.Views_NetworkFee,
xml_table.Views_PublisherCommission,
xml_table.TotalCount
FROM XMLTABLE
(
   XMLNAMESPACES(DEFAULT 'http://affilinet.framework.esbfa/advertiserservices/statistics/messages', 'http://affilinet.framework.esbfa/advertiserservices/statistics/types' AS a, 'http://www.w3.org/2001/XMLSchema-instance' AS i),
   '//GetStatisticsPerPublisherResponse/PublisherStatisticsRecordCollection/a:PublisherStatisticsRecord' PASSING xmldata COLUMNS currency STRING PATH 'a:Currency',
   publisher_id STRING PATH 'a:PublisherId',
   publisher_url STRING PATH 'a:PublisherURL',
   bonus_count_cancelled_count LONG PATH 'a:Bonus/a:Count/a:CancelledCount',
   bonus_count_confirmed_count LONG PATH 'a:Bonus/a:Count/a:ConfirmedCount',
   bonus_count_open_count LONG PATH 'a:Bonus/a:Count/a:OpenCount',
   bonus_network_fee_cancelled_value DOUBLE PATH 'a:Bonus/a:NetworkFee/a:CancelledValue',
   bonus_network_fee_confirmed_value DOUBLE PATH 'a:Bonus/a:NetworkFee/a:ConfirmedValue',
   bonus_network_fee_open_value DOUBLE PATH 'a:Bonus/a:NetworkFee/a:OpenValue',
   bonus_publisher_commission_cancelled_value DOUBLE PATH 'a:Bonus/a:PublisherCommission/a:CancelledValue',
   bonus_publisher_commission_confirmed_value DOUBLE PATH 'a:Bonus/a:PublisherCommission/a:ConfirmedValue',
   bonus_publisher_commission_open_value DOUBLE PATH 'a:Bonus/a:PublisherCommission/a:OpenValue',
   click_outs_total_count_cancelled_count LONG PATH 'a:ClickOuts/a:TotalCount/a:CancelledCount',
   click_outs_total_count_confirmed_count LONG PATH 'a:ClickOuts/a:TotalCount/a:ConfirmedCount',
   click_outs_total_count_open_count LONG PATH 'a:ClickOuts/a:TotalCount/a:OpenCount',
   click_outs_total_net_price_cancelled_value DOUBLE PATH 'a:ClickOuts/a:TotalNetPrice/a:CancelledValue',
   click_outs_total_net_price_confirmed_value DOUBLE PATH 'a:ClickOuts/a:TotalNetPrice/a:ConfirmedValue',
   click_outs_total_net_price_open_value DOUBLE PATH 'a:ClickOuts/a:TotalNetPrice/a:OpenValue',
   click_outs_total_network_fee_cancelled_value DOUBLE PATH 'a:ClickOuts/a:TotalNetworkFee/a:CancelledValue',
   click_outs_total_network_fee_confirmed_value DOUBLE PATH 'a:ClickOuts/a:TotalNetworkFee/a:ConfirmedValue',
   click_outs_total_network_fee_open_value DOUBLE PATH 'a:ClickOuts/a:TotalNetworkFee/a:OpenValue',
   click_outs_total_publisher_commission_cancelled_value DOUBLE PATH 'a:ClickOuts/a:TotalPublisherCommission/a:CancelledValue',
   click_outs_total_publisher_commission_confirmed_value DOUBLE PATH 'a:ClickOuts/a:TotalPublisherCommission/a:ConfirmedValue',
   click_outs_total_publisher_commission_open_value DOUBLE PATH 'a:ClickOuts/a:TotalPublisherCommission/a:OpenValue',
   clicks_gross_count LONG PATH 'a:Clicks/a:GrossCount',
   clicks_net_count LONG PATH 'a:Clicks/a:NetCount',
   clicks_network_fee DOUBLE PATH 'a:Clicks/a:NetworkFee',
   clicks_publisher_commission DOUBLE PATH 'a:Clicks/a:PublisherCommission',
   leads_total_count_cancelled_count LONG PATH 'a:Leads/a:TotalCount/a:CancelledCount',
   leads_total_count_confirmed_count LONG PATH 'a:Leads/a:TotalCount/a:ConfirmedCount',
   leads_total_count_open_count LONG PATH 'a:Leads/a:TotalCount/a:OpenCount',
   leads_total_net_price_cancelled_value DOUBLE PATH 'a:Leads/a:TotalNetPrice/a:CancelledValue',
   leads_total_net_price_confirmed_value DOUBLE PATH 'a:Leads/a:TotalNetPrice/a:ConfirmedValue',
   leads_total_net_price_open_value DOUBLE PATH 'a:Leads/a:TotalNetPrice/a:OpenValue',
   leads_total_network_fee_cancelled_value DOUBLE PATH 'a:Leads/a:TotalNetworkFee/a:CancelledValue',
   leads_total_network_fee_confirmed_value DOUBLE PATH 'a:Leads/a:TotalNetworkFee/a:ConfirmedValue',
   leads_total_network_fee_open_value DOUBLE PATH 'a:Leads/a:TotalNetworkFee/a:OpenValue',
   leads_total_publisher_commission_cancelled_value DOUBLE PATH 'a:Leads/a:TotalPublisherCommission/a:CancelledValue',
   leads_total_publisher_commission_confirmed_value DOUBLE PATH 'a:Leads/a:TotalPublisherCommission/a:ConfirmedValue',
   leads_total_publisher_commission_open_value DOUBLE PATH 'a:Leads/a:TotalPublisherCommission/a:OpenValue',
   net_price_summary_cancelled_value DOUBLE PATH 'a:NetPriceSummary/a:CancelledValue',
   net_price_summary_confirmed_value DOUBLE PATH 'a:NetPriceSummary/a:ConfirmedValue',
   net_price_summary_open_value DOUBLE PATH 'a:NetPriceSummary/a:OpenValue',
   network_fee_summary_cancelled_value DOUBLE PATH 'a:NetworkFeeSummary/a:CancelledValue',
   network_fee_summary_confirmed_value DOUBLE PATH 'a:NetworkFeeSummary/a:ConfirmedValue',
   network_fee_summary_open_value DOUBLE PATH 'a:NetworkFeeSummary/a:OpenValue',
   publisher_commission_summary_cancelled_value DOUBLE PATH 'a:PublisherCommissionSummary/a:CancelledValue',
   publisher_commission_summary_confirmed_value DOUBLE PATH 'a:PublisherCommissionSummary/a:ConfirmedValue',
   publisher_commission_summary_open_value DOUBLE PATH 'a:PublisherCommissionSummary/a:OpenValue',
   sales_total_count_cancelled_count LONG PATH 'a:Sales/a:TotalCount/a:CancelledCount',
   sales_total_count_confirmed_count LONG PATH 'a:Sales/a:TotalCount/a:ConfirmedCount',
   sales_total_count_open_count LONG PATH 'a:Sales/a:TotalCount/a:OpenCount',
   sales_total_net_price_cancelled_value STRING PATH 'a:Sales/a:TotalNetPrice/a:CancelledValue',
   sales_total_net_price_confirmed_value DOUBLE PATH 'a:Sales/a:TotalNetPrice/a:ConfirmedValue',
   sales_total_net_price_open_value DOUBLE PATH 'a:Sales/a:TotalNetPrice/a:OpenValue',
   sales_total_network_fee_cancelled_value DOUBLE PATH 'a:Sales/a:TotalNetworkFee/a:CancelledValue',
   sales_total_network_fee_confirmed_value DOUBLE PATH 'a:Sales/a:TotalNetworkFee/a:ConfirmedValue',
   sales_total_network_fee_open_value DOUBLE PATH 'a:Sales/a:TotalNetworkFee/a:OpenValue',
   sales_total_publisher_commission_cancelled_value DOUBLE PATH 'a:Sales/a:TotalPublisherCommission/a:CancelledValue',
   sales_total_publisher_commission_confirmed_value DOUBLE PATH 'a:Sales/a:TotalPublisherCommission/a:ConfirmedValue',
   sales_total_publisher_commission_open_value DOUBLE PATH 'a:Sales/a:TotalPublisherCommission/a:OpenValue',
   Views_GrossCount LONG PATH 'a:Views/a:GrossCount',
   Views_NetCount LONG PATH 'a:Views/a:NetCount',
   Views_NetworkFee DOUBLE PATH 'a:Views/a:NetworkFee',
   Views_PublisherCommission DOUBLE PATH 'a:Views/a:PublisherCommission',
   TotalCount INTEGER PATH '../../../GetStatisticsPerPublisherResponse/TotalCount'
)
AS xml_table;
END


