-- Name: tableau.datamart_datasource
-- Created: 2015-09-22 10:56:54
-- Updated: 2015-09-28 16:57:29

CREATE VIEW tableau.datamart_datasource
AS

SELECT
  op.opp_id,
  op.case_id,
  op.customer_id,
  op.opp_type,
  op.opp_shipping_region,
  op.opp_shipping_city,
  op.opp_shipping_country,
  op.opp_shipping_zip,
  op.opp_billing_region,
  op.opp_billing_city,
  op.opp_billing_country,
  op.opp_billing_zip,
  op.opp_cancellation_reason,
  op.ops_check_status,
  op.opp_conversion_status,
  op.opp_payment_type,
  op.opp_sales_channel_1,
  op.opp_sales_channel_2,
  op.date_opp_created,
  op.date_opp_confirmed,
  op.date_opp_closed,
  op.date_opp_cancelled,
  op.opp_confirmation_status,

  ord.order_id,
  ord.parent_order_id,
  ord.order_type,
  ord.payment_method,
  ord.order_shipping_region,
  ord.order_shipping_city,
  ord.order_shipping_country,
  ord.order_shipping_zip,
  ord.order_billing_region,
  ord.order_billing_city,
  ord.order_billing_country,
  ord.order_billing_zip,
  ord.order_status,
  ord.order_return_status,
  ord.order_cancellation_status,
  ord.status_balance,
  ord.date_order_created,
  ord.date_order_invoiced,
  ord.date_order_completed,
  ord.date_order_cancelled,
  ord.date_order_shipped,
  ord.date_order_returned,
  ord.order_sales_channel_1,
  ord.order_sales_channel_2,
  ord.after_order_sales_channel,

  cu.customer_acquisition_channel_1,
  cu.customer_acquisition_channel_2,
  cu.customer_segment,
  cu.date_account_created,
  cu.customer_age,
  cu.customer_status,
  cu.has_phone_number,
  cu.has_email,
  cu.has_facebook,
  cu.has_linkedin,
  cu.has_xing,
  cu.is_club_customer,
  cu.domain_page,
  cu.user_type,
  
  ca.case_no,
  ca.case_type,
  ca.case_shipping_region,
  ca.case_shipping_city,
  ca.case_shipping_zip,
  ca.case_shipping_country,
  ca.case_billing_region,
  ca.case_billing_city,
  ca.case_billing_zip,
  ca.case_billing_country,
  ca.case_status,
  ca.case_sales_channel_1,
  ca.case_sales_channel_2,
  ca.case_cancellation_status,
  ca.date_case_created,
  ca.case_customer_age,
  ca.has_follow_on,

  fo.itb4canc,
  fo.itcan,
  fo.itb4ret,
  fo.itret,
  fo.estitret,
  fo.itexp,

  fo.gsb4canc_in_eur,
  fo.gscanc_in_eur,
  fo.gsb4ret_in_eur,
  fo.gret_in_eur,
  fo.ggood_in_eur,
  fo.estgret_in_eur,
  fo.est_goodwill_in_eur,
  fo.gsexp_in_eur,

  fo.nsb4canc_in_eur,
  fo.nscanc_in_eur,
  fo.nsb4ret_in_eur,
  fo.nret_in_eur,
  fo.ngood_in_eur,
  fo.estnret_in_eur,
  fo.estngood_in_eur,
  fo.nsexp_in_eur,

  fo.gsb4canc_in_local_currency,
  fo.gscanc_in_local_currency,
  fo.gsb4ret_in_local_currency,
  fo.gret_in_local_currency,
  fo.ggood_in_local_currency,
  fo.estgret_in_local_currency,
  fo.estggood_in_local_currency,
  fo.gsexp_in_local_currency,

  fo.nsb4canc_in_local_currency,
  fo.nscanc_in_local_currency,
  fo.nsb4ret_in_local_currency,
  fo.nret_in_local_currency,
  fo.ngood_in_local_currency,
  fo.estnret_in_local_currency,
  fo.estngood_in_local_currency,
  fo.nsexp_in_local_currency,

  fo.cogb4canc,
  fo.cogcanc,
  fo.cogb4ret,
  fo.cogret,
  fo.estcogret,
  fo.cogexp,

  fo.netdisc_in_local_currency,
  fo.netdisc_in_eur,
  fo.estnetdisc_in_local_currency,
  fo.estnetdisc_in_eur,

  fo.date_amount_paid,
  fo.billing_total,
  fo.billing_received,
  fo.billing_open,
  fo.billing_vat,
  fo.billing_net_sales
  
FROM datamart.dim_opportunity op
LEFT JOIN datamart.dim_order ord on ord.order_id=op.opp_id
LEFT JOIN datamart.dim_customer cu on cu.customer_id=op.customer_id
LEFT JOIN datamart.dim_case ca ON ca.case_id=op.case_id 
LEFT JOIN datamart.fact_order fo on fo.order_id=ord.order_id


