-- Name: ml.project_compl_customers
-- Created: 2015-04-24 18:19:25
-- Updated: 2015-04-24 18:19:25

CREATE VIEW ml.project_compl_customers AS
SELECT
    customer.customer_id,
	customer.spending_budget_for_jeans_from,
	customer.spending_budget_for_jeans_to,
	customer.spending_budget_for_shoes_from,
	customer.spending_budget_for_shoes_to,
	customer.spending_budget_for_shirts_from,
	customer.spending_budget_for_shirts_to,
	customer.spending_budget_for_jackets_from,
	customer.spending_budget_for_jackets_to,
	survey.is_new_survey,
	survey.typical_style__classic,
    survey.typical_style__country,
    survey.typical_style__adventure,
    survey.typical_style__dark_denim,
    survey.typical_style__sporty,
    survey.typical_style__smart_casual,
    survey.typical_style__prints,
    survey.typical_style__excentric,
    survey.age_felt__18_30,
    survey.age_felt__31_35,
    survey.age_felt__36_45,
    survey.age_felt__46_55,
    survey.work_style__suit,
    survey.work_style__smart_casual,
    survey.work_style__casual,
    survey.work_style__relaxed,
    survey.colors_liked__natural,
    survey.colors_liked__denim,
    survey.colors_liked__classic,
    survey.colors_liked__strong,
    survey.typical_shoes__sneakers,
    survey.typical_shoes__boat_shoes,
    survey.typical_shoes__boots,
    survey.typical_shoes__classic_trendy,
    survey.typical_shoes__desert_boots,
    survey.typical_shoes__sneakers_casual,
    survey.typical_shoes__chelsea_boots,
    survey.typical_shoes__classic_business,
    survey.typical_shoes__chucks,
    survey.typical_shoes__sneakers_trendy,
    survey.typical_shoes__timberland_boots,
    survey.would_never_wear__biglogo,
    survey.would_never_wear__checkered,
    survey.would_never_wear__button_down_shirt,
    survey.would_never_wear__pink_shirt,
    survey.would_never_wear__tommy_hilfiger,
    survey.would_never_wear__print_tshirts,
    survey.would_never_wear__polo_shirt,
    survey.brands_liked__scotch_soda,
    survey.brands_liked__levis,
    survey.brands_liked__tiger,
    survey.brands_liked__bugatti,
    survey.brands_liked__gstar,
    survey.brands_liked__gant,
    survey.brands_liked__selected,
    survey.brands_liked__jack_jones,
    survey.brands_liked__strellson,
    survey.brands_liked__tommy,
    survey.brands_liked__ralphlauren,
    survey.brands_liked__marcopolo,
    survey.underwear_style__boxers,
    survey.underwear_style__trunks,
    survey.underwear_style__briefs
FROM raw.customer AS customer
JOIN ml.customer_survey AS survey
	ON survey.customer_id = customer.customer_id


