-- Name: ml.project_outfit_categories
-- Created: 2015-04-24 18:19:56
-- Updated: 2015-04-24 18:19:56

CREATE VIEW ml.project_outfit_categories AS
SELECT
outfit_id,
SUM(outfit_slot__over_shirt) AS "outfit_slot__over_shirt",
SUM(outfit_slot__shoes) AS "outfit_slot__shoes",
SUM(outfit_slot__shirt) AS "outfit_slot__shirt",
SUM(outfit_slot__trousers) AS "outfit_slot__trousers",
SUM(outfit_slot__belt) AS "outfit_slot__belt",
SUM(outfit_slot__jacket) AS "outfit_slot__jacket",
SUM(outfit_slot__socks) AS "outfit_slot__socks",
SUM(outfit_slot__underwear) AS "outfit_slot__underwear",
SUM(outfit_slot__tie) AS "outfit_slot__tie",
SUM(outfit_slot__suit) AS "outfit_slot__suit",
SUM(outfit_slot__neckwear) AS "outfit_slot__neckwear",
SUM(outfit_slot__headwear) AS "outfit_slot__headwear",
SUM(flat_category__belt) AS "flat_category__belt",
SUM(flat_category__boat_shoe) AS "flat_category__boat_shoe",
SUM(flat_category__boots) AS "flat_category__boots",
SUM(flat_category__caps) AS "flat_category__caps",
SUM(flat_category__cardigan) AS "flat_category__cardigan",
SUM(flat_category__cargo_pants) AS "flat_category__cargo_pants",
SUM(flat_category__casual_belt) AS "flat_category__casual_belt",
SUM(flat_category__casual_lace_up) AS "flat_category__casual_lace_up",
SUM(flat_category__casual_shirt) AS "flat_category__casual_shirt",
SUM(flat_category__chino) AS "flat_category__chino",
SUM(flat_category__dress_pants) AS "flat_category__dress_pants",
SUM(flat_category__dress_shirt) AS "flat_category__dress_shirt",
SUM(flat_category__dress_shoe) AS "flat_category__dress_shoe",
SUM(flat_category__hoodie) AS "flat_category__hoodie",
SUM(flat_category__jeans) AS "flat_category__jeans",
SUM(flat_category__knee_sock) AS "flat_category__knee_sock",
SUM(flat_category__knit_pullover) AS "flat_category__knit_pullover",
SUM(flat_category__leather_jacket) AS "flat_category__leather_jacket",
SUM(flat_category__long_sleeve_t_shirt) AS "flat_category__long_sleeve_t_shirt",
SUM(flat_category__other) AS "flat_category__other",
SUM(flat_category__outdoor_jacket) AS "flat_category__outdoor_jacket",
SUM(flat_category__polo_shirt) AS "flat_category__polo_shirt",
SUM(flat_category__pullover) AS "flat_category__pullover",
SUM(flat_category__sandals) AS "flat_category__sandals",
SUM(flat_category__scarf) AS "flat_category__scarf",
SUM(flat_category__shorts) AS "flat_category__shorts",
SUM(flat_category__sneakers) AS "flat_category__sneakers",
SUM(flat_category__socks) AS "flat_category__socks",
SUM(flat_category__sports) AS "flat_category__sports",
SUM(flat_category__sports_shoes) AS "flat_category__sports_shoes",
SUM(flat_category__suit) AS "flat_category__suit",
SUM(flat_category__suit_jacket) AS "flat_category__suit_jacket",
SUM(flat_category__sweatshirt) AS "flat_category__sweatshirt",
SUM(flat_category__t_shirt_basic) AS "flat_category__t_shirt_basic",
SUM(flat_category__t_shirt_print) AS "flat_category__t_shirt_print",
SUM(flat_category__tie) AS "flat_category__tie",
SUM(flat_category__underwear) AS "flat_category__underwear",
SUM(flat_category__vest) AS "flat_category__vest",
SUM(flat_category__waistcoat) AS "flat_category__waistcoat"
FROM (
SELECT
coa.outfit_id,
CASE WHEN fc.outfit_slot = 'over_shirt' THEN 1 ELSE 0 END AS "outfit_slot__over_shirt",
CASE WHEN fc.outfit_slot = 'shoes' THEN 1 ELSE 0 END AS "outfit_slot__shoes",
CASE WHEN fc.outfit_slot = 'shirt' THEN 1 ELSE 0 END AS "outfit_slot__shirt",
CASE WHEN fc.outfit_slot = 'trousers' THEN 1 ELSE 0 END AS "outfit_slot__trousers",
CASE WHEN fc.outfit_slot = 'belt' THEN 1 ELSE 0 END AS "outfit_slot__belt",
CASE WHEN fc.outfit_slot = 'jacket' THEN 1 ELSE 0 END AS "outfit_slot__jacket",
CASE WHEN fc.outfit_slot = 'socks' THEN 1 ELSE 0 END AS "outfit_slot__socks",
CASE WHEN fc.outfit_slot = 'underwear' THEN 1 ELSE 0 END AS "outfit_slot__underwear",
CASE WHEN fc.outfit_slot = 'tie' THEN 1 ELSE 0 END AS "outfit_slot__tie",
CASE WHEN fc.outfit_slot = 'suit' THEN 1 ELSE 0 END AS "outfit_slot__suit",
CASE WHEN fc.outfit_slot = 'neckwear' THEN 1 ELSE 0 END AS "outfit_slot__neckwear",
CASE WHEN fc.outfit_slot = 'headwear' THEN 1 ELSE 0 END AS "outfit_slot__headwear",
CASE WHEN fc.flat_category = 'belt' THEN 1 ELSE 0 END AS "flat_category__belt",
CASE WHEN fc.flat_category = 'boat_shoe' THEN 1 ELSE 0 END AS "flat_category__boat_shoe",
CASE WHEN fc.flat_category = 'boots' THEN 1 ELSE 0 END AS "flat_category__boots",
CASE WHEN fc.flat_category = 'caps' THEN 1 ELSE 0 END AS "flat_category__caps",
CASE WHEN fc.flat_category = 'cardigan' THEN 1 ELSE 0 END AS "flat_category__cardigan",
CASE WHEN fc.flat_category = 'cargo_pants' THEN 1 ELSE 0 END AS "flat_category__cargo_pants",
CASE WHEN fc.flat_category = 'casual_belt' THEN 1 ELSE 0 END AS "flat_category__casual_belt",
CASE WHEN fc.flat_category = 'casual_lace_up' THEN 1 ELSE 0 END AS "flat_category__casual_lace_up",
CASE WHEN fc.flat_category = 'casual_shirt' THEN 1 ELSE 0 END AS "flat_category__casual_shirt",
CASE WHEN fc.flat_category = 'chino' THEN 1 ELSE 0 END AS "flat_category__chino",
CASE WHEN fc.flat_category = 'dress_pants' THEN 1 ELSE 0 END AS "flat_category__dress_pants",
CASE WHEN fc.flat_category = 'dress_shirt' THEN 1 ELSE 0 END AS "flat_category__dress_shirt",
CASE WHEN fc.flat_category = 'dress_shoe' THEN 1 ELSE 0 END AS "flat_category__dress_shoe",
CASE WHEN fc.flat_category = 'hoodie' THEN 1 ELSE 0 END AS "flat_category__hoodie",
CASE WHEN fc.flat_category = 'jeans' THEN 1 ELSE 0 END AS "flat_category__jeans",
CASE WHEN fc.flat_category = 'knee_sock' THEN 1 ELSE 0 END AS "flat_category__knee_sock",
CASE WHEN fc.flat_category = 'knit_pullover' THEN 1 ELSE 0 END AS "flat_category__knit_pullover",
CASE WHEN fc.flat_category = 'leather_jacket' THEN 1 ELSE 0 END AS "flat_category__leather_jacket",
CASE WHEN fc.flat_category = 'long_sleeve_t_shirt' THEN 1 ELSE 0 END AS "flat_category__long_sleeve_t_shirt",
CASE WHEN fc.flat_category = 'other' THEN 1 ELSE 0 END AS "flat_category__other",
CASE WHEN fc.flat_category = 'outdoor_jacket' THEN 1 ELSE 0 END AS "flat_category__outdoor_jacket",
CASE WHEN fc.flat_category = 'polo_shirt' THEN 1 ELSE 0 END AS "flat_category__polo_shirt",
CASE WHEN fc.flat_category = 'pullover' THEN 1 ELSE 0 END AS "flat_category__pullover",
CASE WHEN fc.flat_category = 'sandals' THEN 1 ELSE 0 END AS "flat_category__sandals",
CASE WHEN fc.flat_category = 'scarf' THEN 1 ELSE 0 END AS "flat_category__scarf",
CASE WHEN fc.flat_category = 'shorts' THEN 1 ELSE 0 END AS "flat_category__shorts",
CASE WHEN fc.flat_category = 'sneakers' THEN 1 ELSE 0 END AS "flat_category__sneakers",
CASE WHEN fc.flat_category = 'socks' THEN 1 ELSE 0 END AS "flat_category__socks",
CASE WHEN fc.flat_category = 'sports' THEN 1 ELSE 0 END AS "flat_category__sports",
CASE WHEN fc.flat_category = 'sports_shoes' THEN 1 ELSE 0 END AS "flat_category__sports_shoes",
CASE WHEN fc.flat_category = 'suit' THEN 1 ELSE 0 END AS "flat_category__suit",
CASE WHEN fc.flat_category = 'suit_jacket' THEN 1 ELSE 0 END AS "flat_category__suit_jacket",
CASE WHEN fc.flat_category = 'sweatshirt' THEN 1 ELSE 0 END AS "flat_category__sweatshirt",
CASE WHEN fc.flat_category = 't_shirt_basic' THEN 1 ELSE 0 END AS "flat_category__t_shirt_basic",
CASE WHEN fc.flat_category = 't_shirt_print' THEN 1 ELSE 0 END AS "flat_category__t_shirt_print",
CASE WHEN fc.flat_category = 'tie' THEN 1 ELSE 0 END AS "flat_category__tie",
CASE WHEN fc.flat_category = 'underwear' THEN 1 ELSE 0 END AS "flat_category__underwear",
CASE WHEN fc.flat_category = 'vest' THEN 1 ELSE 0 END AS "flat_category__vest",
CASE WHEN fc.flat_category = 'waistcoat' THEN 1 ELSE 0 END AS "flat_category__waistcoat"
FROM
"bi.customer_order" co
LEFT JOIN "bi.customer_order_articles" coa ON coa.order_id = co.order_id
LEFT JOIN "bi.article" a ON a.article_id = coa.article_id
LEFT JOIN "ml.amidala_category_flat" acf ON acf.attribute_id = a.article_attribute_id
LEFT JOIN "ml.flat_category" fc ON fc.flat_category = acf.flat_category
WHERE co.date_stylist_picked > '2014-01-01'
AND coa.outfit_id IS NOT NULL
) x
GROUP BY x.outfit_id


